/* Generated by Yosys 0.47+3 (git sha1 2de24dc1c, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module circuit(clk, shared_inp, PRNG, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire [2:0] Ax0;
  wire [2:0] Ax1;
  wire [2:0] Ax2;
  wire [2:0] Ax3;
  wire [2:0] Ay0;
  wire [2:0] Ay1;
  wire [2:0] Ay2;
  wire [2:0] Ay3;
  wire \G1.AND1 ;
  wire \G1.AND5 ;
  wire \G1.AND9 ;
  wire \G1.D1.out ;
  wire \G1.D2.in ;
  wire \G1.D2.out ;
  wire \G1.D3.in ;
  wire \G1.D3.out ;
  wire \G1.D4.in ;
  wire \G1.D4.out ;
  wire \G1.D5.out ;
  wire \G1.D6.in ;
  wire \G1.D6.out ;
  wire \G1.D7.in ;
  wire \G1.D7.out ;
  wire \G1.D8.in ;
  wire \G1.D8.out ;
  wire \G1.D9.out ;
  wire [2:0] \G1.z ;
  wire \G2.AND1 ;
  wire \G2.AND5 ;
  wire \G2.AND9 ;
  wire \G2.D1.out ;
  wire \G2.D2.in ;
  wire \G2.D2.out ;
  wire \G2.D3.in ;
  wire \G2.D3.out ;
  wire \G2.D4.in ;
  wire \G2.D4.out ;
  wire \G2.D5.out ;
  wire \G2.D6.in ;
  wire \G2.D6.out ;
  wire \G2.D7.in ;
  wire \G2.D7.out ;
  wire \G2.D8.in ;
  wire \G2.D8.out ;
  wire \G2.D9.out ;
  wire [2:0] \G2.z ;
  wire \G3.AND1 ;
  wire \G3.AND5 ;
  wire \G3.AND9 ;
  wire \G3.D1.out ;
  wire \G3.D2.in ;
  wire \G3.D2.out ;
  wire \G3.D3.in ;
  wire \G3.D3.out ;
  wire \G3.D4.in ;
  wire \G3.D4.out ;
  wire \G3.D5.out ;
  wire \G3.D6.in ;
  wire \G3.D6.out ;
  wire \G3.D7.in ;
  wire \G3.D7.out ;
  wire \G3.D8.in ;
  wire \G3.D8.out ;
  wire \G3.D9.out ;
  wire [2:0] \G3.z ;
  wire \G4.AND1 ;
  wire \G4.AND5 ;
  wire \G4.AND9 ;
  wire \G4.D1.out ;
  wire \G4.D2.in ;
  wire \G4.D2.out ;
  wire \G4.D3.in ;
  wire \G4.D3.out ;
  wire \G4.D4.in ;
  wire \G4.D4.out ;
  wire \G4.D5.out ;
  wire \G4.D6.in ;
  wire \G4.D6.out ;
  wire \G4.D7.in ;
  wire \G4.D7.out ;
  wire \G4.D8.in ;
  wire \G4.D8.out ;
  wire \G4.D9.out ;
  wire [2:0] \G4.z ;
  wire \G5.AND1 ;
  wire \G5.AND5 ;
  wire \G5.AND9 ;
  wire \G5.D1.out ;
  wire \G5.D2.in ;
  wire \G5.D2.out ;
  wire \G5.D3.in ;
  wire \G5.D3.out ;
  wire \G5.D4.in ;
  wire \G5.D4.out ;
  wire \G5.D5.out ;
  wire \G5.D6.in ;
  wire \G5.D6.out ;
  wire \G5.D7.in ;
  wire \G5.D7.out ;
  wire \G5.D8.in ;
  wire \G5.D8.out ;
  wire \G5.D9.out ;
  wire [2:0] \G5.z ;
  wire \G6.AND1 ;
  wire \G6.AND5 ;
  wire \G6.AND9 ;
  wire \G6.D1.out ;
  wire \G6.D2.in ;
  wire \G6.D2.out ;
  wire \G6.D3.in ;
  wire \G6.D3.out ;
  wire \G6.D4.in ;
  wire \G6.D4.out ;
  wire \G6.D5.out ;
  wire \G6.D6.in ;
  wire \G6.D6.out ;
  wire \G6.D7.in ;
  wire \G6.D7.out ;
  wire \G6.D8.in ;
  wire \G6.D8.out ;
  wire \G6.D9.out ;
  wire [2:0] \G6.z ;
  wire \G7.AND1 ;
  wire \G7.AND5 ;
  wire \G7.AND9 ;
  wire \G7.D1.out ;
  wire \G7.D2.in ;
  wire \G7.D2.out ;
  wire \G7.D3.in ;
  wire \G7.D3.out ;
  wire \G7.D4.in ;
  wire \G7.D4.out ;
  wire \G7.D5.out ;
  wire \G7.D6.in ;
  wire \G7.D6.out ;
  wire \G7.D7.in ;
  wire \G7.D7.out ;
  wire \G7.D8.in ;
  wire \G7.D8.out ;
  wire \G7.D9.out ;
  input [12:0] PRNG;
  wire [12:0] PRNG;
  input clk;
  wire clk;
  wire \for_r52.in ;
  wire \for_r52.out ;
  wire \for_r62.in ;
  wire \for_r62.out ;
  wire \for_r70.in ;
  wire \for_r70.out ;
  wire \for_r71.in ;
  wire \for_r71.out ;
  output [2:0] out;
  wire [2:0] out;
  input [23:0] shared_inp;
  wire [23:0] shared_inp;
  NOT _063_ (
    .A(shared_inp[16]),
    .Y(Ax0[0])
  );
  NOT _064_ (
    .A(shared_inp[17]),
    .Y(Ay0[0])
  );
  NOT _065_ (
    .A(shared_inp[18]),
    .Y(Ax1[0])
  );
  NOT _066_ (
    .A(shared_inp[19]),
    .Y(Ay1[0])
  );
  NOT _067_ (
    .A(shared_inp[20]),
    .Y(Ax2[0])
  );
  NOT _068_ (
    .A(shared_inp[21]),
    .Y(Ay2[0])
  );
  NOT _069_ (
    .A(shared_inp[22]),
    .Y(Ax3[0])
  );
  NOT _070_ (
    .A(shared_inp[23]),
    .Y(Ay3[0])
  );
  XOR _071_ (
    .A(PRNG[11]),
    .B(PRNG[8]),
    .Y(\for_r52.in )
  );
  XOR _072_ (
    .A(PRNG[5]),
    .B(PRNG[2]),
    .Y(\for_r62.in )
  );
  XOR _073_ (
    .A(PRNG[9]),
    .B(PRNG[3]),
    .Y(\for_r70.in )
  );
  XOR _074_ (
    .A(PRNG[7]),
    .B(PRNG[1]),
    .Y(\for_r71.in )
  );
  AND _075_ (
    .A(Ay0[0]),
    .B(Ax0[0]),
    .Y(\G1.AND1 )
  );
  NAND _076_ (
    .A(Ax0[0]),
    .B(shared_inp[9]),
    .Y(_000_)
  );
  XNOR _077_ (
    .A(PRNG[0]),
    .B(_000_),
    .Y(\G1.D2.in )
  );
  NAND _078_ (
    .A(Ax0[0]),
    .B(shared_inp[1]),
    .Y(_001_)
  );
  XNOR _079_ (
    .A(PRNG[1]),
    .B(_001_),
    .Y(\G1.D3.in )
  );
  XNOR _080_ (
    .A(\G1.D1.out ),
    .B(\G1.D3.out ),
    .Y(_002_)
  );
  XNOR _081_ (
    .A(\G1.D2.out ),
    .B(_002_),
    .Y(\G1.z [0])
  );
  AND _082_ (
    .A(shared_inp[9]),
    .B(shared_inp[8]),
    .Y(\G1.AND5 )
  );
  NAND _083_ (
    .A(Ay0[0]),
    .B(shared_inp[8]),
    .Y(_003_)
  );
  XNOR _084_ (
    .A(PRNG[0]),
    .B(_003_),
    .Y(\G1.D4.in )
  );
  NAND _085_ (
    .A(shared_inp[1]),
    .B(shared_inp[8]),
    .Y(_004_)
  );
  XNOR _086_ (
    .A(PRNG[2]),
    .B(_004_),
    .Y(\G1.D6.in )
  );
  XNOR _087_ (
    .A(\G1.D4.out ),
    .B(\G1.D6.out ),
    .Y(_005_)
  );
  XNOR _088_ (
    .A(\G1.D5.out ),
    .B(_005_),
    .Y(\G1.z [1])
  );
  AND _089_ (
    .A(shared_inp[1]),
    .B(shared_inp[0]),
    .Y(\G1.AND9 )
  );
  NAND _090_ (
    .A(Ay0[0]),
    .B(shared_inp[0]),
    .Y(_006_)
  );
  XNOR _091_ (
    .A(PRNG[1]),
    .B(_006_),
    .Y(\G1.D7.in )
  );
  NAND _092_ (
    .A(shared_inp[9]),
    .B(shared_inp[0]),
    .Y(_007_)
  );
  XNOR _093_ (
    .A(PRNG[2]),
    .B(_007_),
    .Y(\G1.D8.in )
  );
  XNOR _094_ (
    .A(\G1.D7.out ),
    .B(\G1.D9.out ),
    .Y(_008_)
  );
  XNOR _095_ (
    .A(\G1.D8.out ),
    .B(_008_),
    .Y(\G1.z [2])
  );
  DFF _096_ (
    .C(clk),
    .D(\G1.AND1 ),
    .Q(\G1.D1.out )
  );
  DFF _097_ (
    .C(clk),
    .D(\G1.D2.in ),
    .Q(\G1.D2.out )
  );
  DFF _098_ (
    .C(clk),
    .D(\G1.D3.in ),
    .Q(\G1.D3.out )
  );
  DFF _099_ (
    .C(clk),
    .D(\G1.D4.in ),
    .Q(\G1.D4.out )
  );
  DFF _100_ (
    .C(clk),
    .D(\G1.AND5 ),
    .Q(\G1.D5.out )
  );
  DFF _101_ (
    .C(clk),
    .D(\G1.D6.in ),
    .Q(\G1.D6.out )
  );
  DFF _102_ (
    .C(clk),
    .D(\G1.D7.in ),
    .Q(\G1.D7.out )
  );
  DFF _103_ (
    .C(clk),
    .D(\G1.D8.in ),
    .Q(\G1.D8.out )
  );
  DFF _104_ (
    .C(clk),
    .D(\G1.AND9 ),
    .Q(\G1.D9.out )
  );
  AND _105_ (
    .A(Ay1[0]),
    .B(Ax1[0]),
    .Y(\G2.AND1 )
  );
  NAND _106_ (
    .A(Ax1[0]),
    .B(shared_inp[11]),
    .Y(_009_)
  );
  XNOR _107_ (
    .A(PRNG[3]),
    .B(_009_),
    .Y(\G2.D2.in )
  );
  NAND _108_ (
    .A(Ax1[0]),
    .B(shared_inp[3]),
    .Y(_010_)
  );
  XNOR _109_ (
    .A(PRNG[4]),
    .B(_010_),
    .Y(\G2.D3.in )
  );
  XNOR _110_ (
    .A(\G2.D1.out ),
    .B(\G2.D3.out ),
    .Y(_011_)
  );
  XNOR _111_ (
    .A(\G2.D2.out ),
    .B(_011_),
    .Y(\G2.z [0])
  );
  AND _112_ (
    .A(shared_inp[11]),
    .B(shared_inp[10]),
    .Y(\G2.AND5 )
  );
  NAND _113_ (
    .A(Ay1[0]),
    .B(shared_inp[10]),
    .Y(_012_)
  );
  XNOR _114_ (
    .A(PRNG[3]),
    .B(_012_),
    .Y(\G2.D4.in )
  );
  NAND _115_ (
    .A(shared_inp[3]),
    .B(shared_inp[10]),
    .Y(_013_)
  );
  XNOR _116_ (
    .A(PRNG[5]),
    .B(_013_),
    .Y(\G2.D6.in )
  );
  XNOR _117_ (
    .A(\G2.D4.out ),
    .B(\G2.D6.out ),
    .Y(_014_)
  );
  XNOR _118_ (
    .A(\G2.D5.out ),
    .B(_014_),
    .Y(\G2.z [1])
  );
  AND _119_ (
    .A(shared_inp[3]),
    .B(shared_inp[2]),
    .Y(\G2.AND9 )
  );
  NAND _120_ (
    .A(Ay1[0]),
    .B(shared_inp[2]),
    .Y(_015_)
  );
  XNOR _121_ (
    .A(PRNG[4]),
    .B(_015_),
    .Y(\G2.D7.in )
  );
  NAND _122_ (
    .A(shared_inp[11]),
    .B(shared_inp[2]),
    .Y(_016_)
  );
  XNOR _123_ (
    .A(PRNG[5]),
    .B(_016_),
    .Y(\G2.D8.in )
  );
  XNOR _124_ (
    .A(\G2.D7.out ),
    .B(\G2.D9.out ),
    .Y(_017_)
  );
  XNOR _125_ (
    .A(\G2.D8.out ),
    .B(_017_),
    .Y(\G2.z [2])
  );
  DFF _126_ (
    .C(clk),
    .D(\G2.AND1 ),
    .Q(\G2.D1.out )
  );
  DFF _127_ (
    .C(clk),
    .D(\G2.D2.in ),
    .Q(\G2.D2.out )
  );
  DFF _128_ (
    .C(clk),
    .D(\G2.D3.in ),
    .Q(\G2.D3.out )
  );
  DFF _129_ (
    .C(clk),
    .D(\G2.D4.in ),
    .Q(\G2.D4.out )
  );
  DFF _130_ (
    .C(clk),
    .D(\G2.AND5 ),
    .Q(\G2.D5.out )
  );
  DFF _131_ (
    .C(clk),
    .D(\G2.D6.in ),
    .Q(\G2.D6.out )
  );
  DFF _132_ (
    .C(clk),
    .D(\G2.D7.in ),
    .Q(\G2.D7.out )
  );
  DFF _133_ (
    .C(clk),
    .D(\G2.D8.in ),
    .Q(\G2.D8.out )
  );
  DFF _134_ (
    .C(clk),
    .D(\G2.AND9 ),
    .Q(\G2.D9.out )
  );
  AND _135_ (
    .A(Ay2[0]),
    .B(Ax2[0]),
    .Y(\G3.AND1 )
  );
  NAND _136_ (
    .A(Ax2[0]),
    .B(shared_inp[13]),
    .Y(_018_)
  );
  XNOR _137_ (
    .A(PRNG[6]),
    .B(_018_),
    .Y(\G3.D2.in )
  );
  NAND _138_ (
    .A(Ax2[0]),
    .B(shared_inp[5]),
    .Y(_019_)
  );
  XNOR _139_ (
    .A(PRNG[7]),
    .B(_019_),
    .Y(\G3.D3.in )
  );
  XNOR _140_ (
    .A(\G3.D1.out ),
    .B(\G3.D3.out ),
    .Y(_020_)
  );
  XNOR _141_ (
    .A(\G3.D2.out ),
    .B(_020_),
    .Y(\G3.z [0])
  );
  AND _142_ (
    .A(shared_inp[13]),
    .B(shared_inp[12]),
    .Y(\G3.AND5 )
  );
  NAND _143_ (
    .A(Ay2[0]),
    .B(shared_inp[12]),
    .Y(_021_)
  );
  XNOR _144_ (
    .A(PRNG[6]),
    .B(_021_),
    .Y(\G3.D4.in )
  );
  NAND _145_ (
    .A(shared_inp[5]),
    .B(shared_inp[12]),
    .Y(_022_)
  );
  XNOR _146_ (
    .A(PRNG[8]),
    .B(_022_),
    .Y(\G3.D6.in )
  );
  XNOR _147_ (
    .A(\G3.D4.out ),
    .B(\G3.D6.out ),
    .Y(_023_)
  );
  XNOR _148_ (
    .A(\G3.D5.out ),
    .B(_023_),
    .Y(\G3.z [1])
  );
  AND _149_ (
    .A(shared_inp[5]),
    .B(shared_inp[4]),
    .Y(\G3.AND9 )
  );
  NAND _150_ (
    .A(Ay2[0]),
    .B(shared_inp[4]),
    .Y(_024_)
  );
  XNOR _151_ (
    .A(PRNG[7]),
    .B(_024_),
    .Y(\G3.D7.in )
  );
  NAND _152_ (
    .A(shared_inp[13]),
    .B(shared_inp[4]),
    .Y(_025_)
  );
  XNOR _153_ (
    .A(PRNG[8]),
    .B(_025_),
    .Y(\G3.D8.in )
  );
  XNOR _154_ (
    .A(\G3.D7.out ),
    .B(\G3.D9.out ),
    .Y(_026_)
  );
  XNOR _155_ (
    .A(\G3.D8.out ),
    .B(_026_),
    .Y(\G3.z [2])
  );
  DFF _156_ (
    .C(clk),
    .D(\G3.AND1 ),
    .Q(\G3.D1.out )
  );
  DFF _157_ (
    .C(clk),
    .D(\G3.D2.in ),
    .Q(\G3.D2.out )
  );
  DFF _158_ (
    .C(clk),
    .D(\G3.D3.in ),
    .Q(\G3.D3.out )
  );
  DFF _159_ (
    .C(clk),
    .D(\G3.D4.in ),
    .Q(\G3.D4.out )
  );
  DFF _160_ (
    .C(clk),
    .D(\G3.AND5 ),
    .Q(\G3.D5.out )
  );
  DFF _161_ (
    .C(clk),
    .D(\G3.D6.in ),
    .Q(\G3.D6.out )
  );
  DFF _162_ (
    .C(clk),
    .D(\G3.D7.in ),
    .Q(\G3.D7.out )
  );
  DFF _163_ (
    .C(clk),
    .D(\G3.D8.in ),
    .Q(\G3.D8.out )
  );
  DFF _164_ (
    .C(clk),
    .D(\G3.AND9 ),
    .Q(\G3.D9.out )
  );
  AND _165_ (
    .A(Ay3[0]),
    .B(Ax3[0]),
    .Y(\G4.AND1 )
  );
  NAND _166_ (
    .A(Ax3[0]),
    .B(shared_inp[15]),
    .Y(_027_)
  );
  XNOR _167_ (
    .A(PRNG[9]),
    .B(_027_),
    .Y(\G4.D2.in )
  );
  NAND _168_ (
    .A(Ax3[0]),
    .B(shared_inp[7]),
    .Y(_028_)
  );
  XNOR _169_ (
    .A(PRNG[10]),
    .B(_028_),
    .Y(\G4.D3.in )
  );
  XNOR _170_ (
    .A(\G4.D1.out ),
    .B(\G4.D3.out ),
    .Y(_029_)
  );
  XNOR _171_ (
    .A(\G4.D2.out ),
    .B(_029_),
    .Y(\G4.z [0])
  );
  AND _172_ (
    .A(shared_inp[15]),
    .B(shared_inp[14]),
    .Y(\G4.AND5 )
  );
  NAND _173_ (
    .A(Ay3[0]),
    .B(shared_inp[14]),
    .Y(_030_)
  );
  XNOR _174_ (
    .A(PRNG[9]),
    .B(_030_),
    .Y(\G4.D4.in )
  );
  NAND _175_ (
    .A(shared_inp[7]),
    .B(shared_inp[14]),
    .Y(_031_)
  );
  XNOR _176_ (
    .A(PRNG[11]),
    .B(_031_),
    .Y(\G4.D6.in )
  );
  XNOR _177_ (
    .A(\G4.D4.out ),
    .B(\G4.D6.out ),
    .Y(_032_)
  );
  XNOR _178_ (
    .A(\G4.D5.out ),
    .B(_032_),
    .Y(\G4.z [1])
  );
  AND _179_ (
    .A(shared_inp[7]),
    .B(shared_inp[6]),
    .Y(\G4.AND9 )
  );
  NAND _180_ (
    .A(Ay3[0]),
    .B(shared_inp[6]),
    .Y(_033_)
  );
  XNOR _181_ (
    .A(PRNG[10]),
    .B(_033_),
    .Y(\G4.D7.in )
  );
  NAND _182_ (
    .A(shared_inp[15]),
    .B(shared_inp[6]),
    .Y(_034_)
  );
  XNOR _183_ (
    .A(PRNG[11]),
    .B(_034_),
    .Y(\G4.D8.in )
  );
  XNOR _184_ (
    .A(\G4.D7.out ),
    .B(\G4.D9.out ),
    .Y(_035_)
  );
  XNOR _185_ (
    .A(\G4.D8.out ),
    .B(_035_),
    .Y(\G4.z [2])
  );
  DFF _186_ (
    .C(clk),
    .D(\G4.AND1 ),
    .Q(\G4.D1.out )
  );
  DFF _187_ (
    .C(clk),
    .D(\G4.D2.in ),
    .Q(\G4.D2.out )
  );
  DFF _188_ (
    .C(clk),
    .D(\G4.D3.in ),
    .Q(\G4.D3.out )
  );
  DFF _189_ (
    .C(clk),
    .D(\G4.D4.in ),
    .Q(\G4.D4.out )
  );
  DFF _190_ (
    .C(clk),
    .D(\G4.AND5 ),
    .Q(\G4.D5.out )
  );
  DFF _191_ (
    .C(clk),
    .D(\G4.D6.in ),
    .Q(\G4.D6.out )
  );
  DFF _192_ (
    .C(clk),
    .D(\G4.D7.in ),
    .Q(\G4.D7.out )
  );
  DFF _193_ (
    .C(clk),
    .D(\G4.D8.in ),
    .Q(\G4.D8.out )
  );
  DFF _194_ (
    .C(clk),
    .D(\G4.AND9 ),
    .Q(\G4.D9.out )
  );
  AND _195_ (
    .A(\G2.z [0]),
    .B(\G1.z [0]),
    .Y(\G5.AND1 )
  );
  NAND _196_ (
    .A(\G1.z [0]),
    .B(\G2.z [1]),
    .Y(_036_)
  );
  XNOR _197_ (
    .A(PRNG[6]),
    .B(_036_),
    .Y(\G5.D2.in )
  );
  NAND _198_ (
    .A(\G1.z [0]),
    .B(\G2.z [2]),
    .Y(_037_)
  );
  XNOR _199_ (
    .A(PRNG[10]),
    .B(_037_),
    .Y(\G5.D3.in )
  );
  XNOR _200_ (
    .A(\G5.D1.out ),
    .B(\G5.D3.out ),
    .Y(_038_)
  );
  XNOR _201_ (
    .A(\G5.D2.out ),
    .B(_038_),
    .Y(\G5.z [0])
  );
  AND _202_ (
    .A(\G2.z [1]),
    .B(\G1.z [1]),
    .Y(\G5.AND5 )
  );
  NAND _203_ (
    .A(\G2.z [0]),
    .B(\G1.z [1]),
    .Y(_039_)
  );
  XNOR _204_ (
    .A(PRNG[6]),
    .B(_039_),
    .Y(\G5.D4.in )
  );
  NAND _205_ (
    .A(\G2.z [2]),
    .B(\G1.z [1]),
    .Y(_040_)
  );
  XNOR _206_ (
    .A(\for_r52.out ),
    .B(_040_),
    .Y(\G5.D6.in )
  );
  XNOR _207_ (
    .A(\G5.D4.out ),
    .B(\G5.D6.out ),
    .Y(_041_)
  );
  XNOR _208_ (
    .A(\G5.D5.out ),
    .B(_041_),
    .Y(\G5.z [1])
  );
  AND _209_ (
    .A(\G2.z [2]),
    .B(\G1.z [2]),
    .Y(\G5.AND9 )
  );
  NAND _210_ (
    .A(\G2.z [0]),
    .B(\G1.z [2]),
    .Y(_042_)
  );
  XNOR _211_ (
    .A(PRNG[10]),
    .B(_042_),
    .Y(\G5.D7.in )
  );
  NAND _212_ (
    .A(\G2.z [1]),
    .B(\G1.z [2]),
    .Y(_043_)
  );
  XNOR _213_ (
    .A(\for_r52.out ),
    .B(_043_),
    .Y(\G5.D8.in )
  );
  XNOR _214_ (
    .A(\G5.D7.out ),
    .B(\G5.D9.out ),
    .Y(_044_)
  );
  XNOR _215_ (
    .A(\G5.D8.out ),
    .B(_044_),
    .Y(\G5.z [2])
  );
  DFF _216_ (
    .C(clk),
    .D(\G5.AND1 ),
    .Q(\G5.D1.out )
  );
  DFF _217_ (
    .C(clk),
    .D(\G5.D2.in ),
    .Q(\G5.D2.out )
  );
  DFF _218_ (
    .C(clk),
    .D(\G5.D3.in ),
    .Q(\G5.D3.out )
  );
  DFF _219_ (
    .C(clk),
    .D(\G5.D4.in ),
    .Q(\G5.D4.out )
  );
  DFF _220_ (
    .C(clk),
    .D(\G5.AND5 ),
    .Q(\G5.D5.out )
  );
  DFF _221_ (
    .C(clk),
    .D(\G5.D6.in ),
    .Q(\G5.D6.out )
  );
  DFF _222_ (
    .C(clk),
    .D(\G5.D7.in ),
    .Q(\G5.D7.out )
  );
  DFF _223_ (
    .C(clk),
    .D(\G5.D8.in ),
    .Q(\G5.D8.out )
  );
  DFF _224_ (
    .C(clk),
    .D(\G5.AND9 ),
    .Q(\G5.D9.out )
  );
  AND _225_ (
    .A(\G4.z [0]),
    .B(\G3.z [0]),
    .Y(\G6.AND1 )
  );
  NAND _226_ (
    .A(\G3.z [0]),
    .B(\G4.z [1]),
    .Y(_045_)
  );
  XNOR _227_ (
    .A(PRNG[0]),
    .B(_045_),
    .Y(\G6.D2.in )
  );
  NAND _228_ (
    .A(\G3.z [0]),
    .B(\G4.z [2]),
    .Y(_046_)
  );
  XNOR _229_ (
    .A(PRNG[4]),
    .B(_046_),
    .Y(\G6.D3.in )
  );
  XNOR _230_ (
    .A(\G6.D1.out ),
    .B(\G6.D3.out ),
    .Y(_047_)
  );
  XNOR _231_ (
    .A(\G6.D2.out ),
    .B(_047_),
    .Y(\G6.z [0])
  );
  AND _232_ (
    .A(\G4.z [1]),
    .B(\G3.z [1]),
    .Y(\G6.AND5 )
  );
  NAND _233_ (
    .A(\G4.z [0]),
    .B(\G3.z [1]),
    .Y(_048_)
  );
  XNOR _234_ (
    .A(PRNG[0]),
    .B(_048_),
    .Y(\G6.D4.in )
  );
  NAND _235_ (
    .A(\G4.z [2]),
    .B(\G3.z [1]),
    .Y(_049_)
  );
  XNOR _236_ (
    .A(\for_r62.out ),
    .B(_049_),
    .Y(\G6.D6.in )
  );
  XNOR _237_ (
    .A(\G6.D4.out ),
    .B(\G6.D6.out ),
    .Y(_050_)
  );
  XNOR _238_ (
    .A(\G6.D5.out ),
    .B(_050_),
    .Y(\G6.z [1])
  );
  AND _239_ (
    .A(\G4.z [2]),
    .B(\G3.z [2]),
    .Y(\G6.AND9 )
  );
  NAND _240_ (
    .A(\G4.z [0]),
    .B(\G3.z [2]),
    .Y(_051_)
  );
  XNOR _241_ (
    .A(PRNG[4]),
    .B(_051_),
    .Y(\G6.D7.in )
  );
  NAND _242_ (
    .A(\G4.z [1]),
    .B(\G3.z [2]),
    .Y(_052_)
  );
  XNOR _243_ (
    .A(\for_r62.out ),
    .B(_052_),
    .Y(\G6.D8.in )
  );
  XNOR _244_ (
    .A(\G6.D7.out ),
    .B(\G6.D9.out ),
    .Y(_053_)
  );
  XNOR _245_ (
    .A(\G6.D8.out ),
    .B(_053_),
    .Y(\G6.z [2])
  );
  DFF _246_ (
    .C(clk),
    .D(\G6.AND1 ),
    .Q(\G6.D1.out )
  );
  DFF _247_ (
    .C(clk),
    .D(\G6.D2.in ),
    .Q(\G6.D2.out )
  );
  DFF _248_ (
    .C(clk),
    .D(\G6.D3.in ),
    .Q(\G6.D3.out )
  );
  DFF _249_ (
    .C(clk),
    .D(\G6.D4.in ),
    .Q(\G6.D4.out )
  );
  DFF _250_ (
    .C(clk),
    .D(\G6.AND5 ),
    .Q(\G6.D5.out )
  );
  DFF _251_ (
    .C(clk),
    .D(\G6.D6.in ),
    .Q(\G6.D6.out )
  );
  DFF _252_ (
    .C(clk),
    .D(\G6.D7.in ),
    .Q(\G6.D7.out )
  );
  DFF _253_ (
    .C(clk),
    .D(\G6.D8.in ),
    .Q(\G6.D8.out )
  );
  DFF _254_ (
    .C(clk),
    .D(\G6.AND9 ),
    .Q(\G6.D9.out )
  );
  AND _255_ (
    .A(\G6.z [0]),
    .B(\G5.z [0]),
    .Y(\G7.AND1 )
  );
  NAND _256_ (
    .A(\G5.z [0]),
    .B(\G6.z [1]),
    .Y(_054_)
  );
  XNOR _257_ (
    .A(\for_r71.out ),
    .B(_054_),
    .Y(\G7.D2.in )
  );
  NAND _258_ (
    .A(\G5.z [0]),
    .B(\G6.z [2]),
    .Y(_055_)
  );
  XNOR _259_ (
    .A(\for_r70.out ),
    .B(_055_),
    .Y(\G7.D3.in )
  );
  XNOR _260_ (
    .A(\G7.D1.out ),
    .B(\G7.D3.out ),
    .Y(_056_)
  );
  XNOR _261_ (
    .A(\G7.D2.out ),
    .B(_056_),
    .Y(out[0])
  );
  AND _262_ (
    .A(\G6.z [1]),
    .B(\G5.z [1]),
    .Y(\G7.AND5 )
  );
  NAND _263_ (
    .A(\G6.z [0]),
    .B(\G5.z [1]),
    .Y(_057_)
  );
  XNOR _264_ (
    .A(\for_r71.out ),
    .B(_057_),
    .Y(\G7.D4.in )
  );
  NAND _265_ (
    .A(\G6.z [2]),
    .B(\G5.z [1]),
    .Y(_058_)
  );
  XNOR _266_ (
    .A(PRNG[12]),
    .B(_058_),
    .Y(\G7.D6.in )
  );
  XNOR _267_ (
    .A(\G7.D4.out ),
    .B(\G7.D6.out ),
    .Y(_059_)
  );
  XNOR _268_ (
    .A(\G7.D5.out ),
    .B(_059_),
    .Y(out[1])
  );
  AND _269_ (
    .A(\G6.z [2]),
    .B(\G5.z [2]),
    .Y(\G7.AND9 )
  );
  NAND _270_ (
    .A(\G6.z [0]),
    .B(\G5.z [2]),
    .Y(_060_)
  );
  XNOR _271_ (
    .A(\for_r70.out ),
    .B(_060_),
    .Y(\G7.D7.in )
  );
  NAND _272_ (
    .A(\G6.z [1]),
    .B(\G5.z [2]),
    .Y(_061_)
  );
  XNOR _273_ (
    .A(PRNG[12]),
    .B(_061_),
    .Y(\G7.D8.in )
  );
  XNOR _274_ (
    .A(\G7.D7.out ),
    .B(\G7.D9.out ),
    .Y(_062_)
  );
  XNOR _275_ (
    .A(\G7.D8.out ),
    .B(_062_),
    .Y(out[2])
  );
  DFF _276_ (
    .C(clk),
    .D(\G7.AND1 ),
    .Q(\G7.D1.out )
  );
  DFF _277_ (
    .C(clk),
    .D(\G7.D2.in ),
    .Q(\G7.D2.out )
  );
  DFF _278_ (
    .C(clk),
    .D(\G7.D3.in ),
    .Q(\G7.D3.out )
  );
  DFF _279_ (
    .C(clk),
    .D(\G7.D4.in ),
    .Q(\G7.D4.out )
  );
  DFF _280_ (
    .C(clk),
    .D(\G7.AND5 ),
    .Q(\G7.D5.out )
  );
  DFF _281_ (
    .C(clk),
    .D(\G7.D6.in ),
    .Q(\G7.D6.out )
  );
  DFF _282_ (
    .C(clk),
    .D(\G7.D7.in ),
    .Q(\G7.D7.out )
  );
  DFF _283_ (
    .C(clk),
    .D(\G7.D8.in ),
    .Q(\G7.D8.out )
  );
  DFF _284_ (
    .C(clk),
    .D(\G7.AND9 ),
    .Q(\G7.D9.out )
  );
  DFF _285_ (
    .C(clk),
    .D(\for_r52.in ),
    .Q(\for_r52.out )
  );
  DFF _286_ (
    .C(clk),
    .D(\for_r62.in ),
    .Q(\for_r62.out )
  );
  DFF _287_ (
    .C(clk),
    .D(\for_r70.in ),
    .Q(\for_r70.out )
  );
  DFF _288_ (
    .C(clk),
    .D(\for_r71.in ),
    .Q(\for_r71.out )
  );
  assign Ax0[2:1] = { shared_inp[0], shared_inp[8] };
  assign Ax1[2:1] = { shared_inp[2], shared_inp[10] };
  assign Ax2[2:1] = { shared_inp[4], shared_inp[12] };
  assign Ax3[2:1] = { shared_inp[6], shared_inp[14] };
  assign Ay0[2:1] = { shared_inp[1], shared_inp[9] };
  assign Ay1[2:1] = { shared_inp[3], shared_inp[11] };
  assign Ay2[2:1] = { shared_inp[5], shared_inp[13] };
  assign Ay3[2:1] = { shared_inp[7], shared_inp[15] };
endmodule
